apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secret-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vault-secret-operator
  template:
    metadata:
      labels:
        name: vault-secret-operator
    spec:
      serviceAccountName: vault-secret-operator
      containers:
        - name: vault-secret-operator
          # Replace this with the built image name
          image: readytalk/vault-secret-operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - vault-secret-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vault-secret-operator"
