apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "vault-secret-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vault-secret-operator.name" . }}
    helm.sh/chart: {{ include "vault-secret-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vault-secret-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vault-secret-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "vault-secret-operator.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - vault-secret-operator
          env:
            - name: VAULT_ADDR
              value: {{ .Values.vault.vaultAddr }}
            - name: VAULT_TOKEN
              value: {{ .Values.vault.vaultToken }}
            - name: VAULT_SECRET_PATH
              value: {{ .Values.vault.vaultSecretPath }}
            - name: MINIMUM_REFRESH_RATE
              value: {{ .Values.controller.minimumRefreshRate }}           
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vault-secret-operator"
